[style.command_name]
foreground = "red"

[style.description]
foreground = "cyan"

[style.example_text]
foreground = "green"

[style.example_code]
foreground = "white"

[style.example_variable]
foreground = "magenta"
